/**
 * 체크리스트 표준시트 기본값 — 렛츠 제공 양식(ver.20260703)에서 생성.
 * 테넌트에 표준시트가 하나도 없을 때 최초 1회 시드한다 (lib/checklists/server.ts).
 * 이후 수정은 설정 > 체크리스트 표준시트에서 하며, 이 파일은 다시 쓰지 않는다.
 */

import type { ChecklistKind } from "./kinds";

export type DefaultTemplateItem = {
  phase: string | null;
  category: string | null;
  subcategory: string | null;
  title: string;
  offsetDays: number | null;
  quantity: string | null;
  note: string | null;
};

export type DefaultTemplate = {
  kind: ChecklistKind;
  name: string;
  sortOrder: number;
  items: DefaultTemplateItem[];
};

export const DEFAULT_CHECKLIST_TEMPLATES: DefaultTemplate[] = [
  {
    kind: "common",
    name: "공통 체크리스트",
    sortOrder: 0,
    items: [
      { phase: "행사전", category: null, subcategory: "계약", title: "계약 필요 서류 확인 및 경영지원팀 요청", offsetDays: -40, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "계약", title: "계약 서류 준비 및 발주기관 송부 완료", offsetDays: -35, quantity: null, note: "계약 진행률 50%" },
      { phase: "행사전", category: null, subcategory: "계약", title: "계약 체결 완료", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "착수보고", title: "계약서 DB(메신저)방 및 네이버 웍스 드라이브 업로드", offsetDays: -28, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "계약서 완료", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "착수보고", title: "내부 착수보고서 1차 작성 및 제출", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "착수보고", title: "내부 착수보고서 최종 수정 및 제출", offsetDays: -1, quantity: null, note: "무슨 사유로 변경(8/30 -> 9/6)" },
      { phase: "행사전", category: null, subcategory: "착수보고", title: "착수보고회 일정 확정", offsetDays: -28, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "착수보고", title: "착수보고회 체크리스트 작성", offsetDays: -28, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "착수보고", title: "마감일 체크리스트 작성", offsetDays: -28, quantity: null, note: "발주처와의 업무분장용 체크리스트" },
      { phase: "행사전", category: null, subcategory: "착수보고", title: "착수보고회 회의록 작성 및 송부", offsetDays: -26, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "착수보고", title: "착수보고회 회의록 최종본 공유(사내 게시판)", offsetDays: -26, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "착수보고 완료", offsetDays: -26, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 후보 리스트업", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 후보별 견적서 입수(견적비교용)", offsetDays: -29, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 결제 방법 확인", offsetDays: -29, quantity: null, note: "(결제방식) 카드 vs 입금(세금계산서, 사업자등록증, 통장사본" },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 확정 및 2차 견적서 및 정산 관련 자료 입수", offsetDays: -28, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 대관 내부 품의 결재", offsetDays: -28, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "현장 답사 일정 체크", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 체크리스트 1차 확인(점검 항목 확인)", offsetDays: -25, quantity: null, note: "답사/유선 확인 전, 점검해야 할 사항 업데이트" },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 체크리스트 2차 확인(답사/ 유선 점검 결과 작성)", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 답사보고서 작성 및 공유", offsetDays: -25, quantity: null, note: "※ 프로그램 특성상 확인되어야 할 사항이 많을 경우 별도로 보고서 작성" },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 최종 견적서 입수", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 체크리스트 최종 확인", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "시설대관", title: "숙소 및 강의장 견적서 공유(사내 드라이브)", offsetDays: -10, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "숙소 및 강의장 확정", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "버스", title: "버스 경로 확인", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "버스", title: "버스 업체 확인 및 업체별 견적서 입수(견적 비교용)", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "버스", title: "버스 업체 확정 및 최종 견적서, 정산 자료 입수", offsetDays: -20, quantity: null, note: "(결제방식) 카드 vs 입금(세금계산서, 사업자등록증, 통장사본" },
      { phase: "행사전", category: null, subcategory: "버스", title: "버스 차량번호, 기사님 번호 및 결제 방법 확인", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "버스", title: "버스 내부 품의 결재", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "버스", title: "버스 견적서 공유(사내 드라이브)", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "버스", title: "버스 승/하차 지점 확정", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "버스", title: "버스 운행 안내(승/하차 지점, 시간 등) 자료 작성", offsetDays: -7, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "버스 업체 확정 및 버스 안내 사항 확인", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "홍보 포스터/현수막 문구 구성 및  내부 컨펌", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "홍보 포스터/현수막 문구 클라이언트 확인", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "홍보 포스터/현수막 디자인 제작 및 내부 컨펌", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "홍보 포스터/현수막 디자인 클라이언트 확인", offsetDays: -28, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "홍보 포스터/현수막 출력 내부 품의 결재", offsetDays: -24, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "홍보 포스터/현수막 출력 요청", offsetDays: -24, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "홍보 포스터/현수막 수령", offsetDays: -20, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "홍보 디자인물 제작 완료", offsetDays: -24, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "온라인 홍보 게시글 문구 작성 및 내부 컨펌", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "온라인 홍보처 리스트업 및 확정", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "온라인 홍보 의뢰(사이트 홍보물 게시 등)", offsetDays: -24, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "온라인 홍보 게제 화면 캡처물 취합", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "오프라인 홍보 포스터/현수막 설치", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "홍보", title: "오프라인 홍보 포스터/현수막 게시 사진 촬영", offsetDays: -20, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "(온/오프라인) 홍보 진행 완료", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "모집", title: "참가자 모집 사이트 개설", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "모집", title: "모집공고문 작성 및 내부 컨펌", offsetDays: -30, quantity: null, note: "발주기관 모집공고문이 있을 경우, 대체 가능" },
      { phase: "행사전", category: null, subcategory: "모집", title: "모집공고문 클라이언트 컨펌", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "모집", title: "참가자 모집/홍보 현황 1차 확인", offsetDays: -28, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "모집", title: "참가자 모집/홍보 현황 2차 확인", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "모집", title: "참가자 모집/홍보 현황 3차 확인(최종)", offsetDays: -14, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "참가자 모집 완료", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "선정", title: "선정 안내문자 작성 및 내부컨펌", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "선정", title: "선정 안내문자 클라이언트 컨펌", offsetDays: -18, quantity: null, note: "미선정자 대상 안내문자 발송 여부도 확인" },
      { phase: "행사전", category: null, subcategory: "선정", title: "최종 선정자 확정", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "선정", title: "선정자 발표(선정 안내문자 송부)", offsetDays: -14, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "참가자 선정 확정", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "보도자료", title: "사전 보도자료 작성 및 내부 컨펌", offsetDays: -27, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "보도자료", title: "사전 보도자료 클라이언트 확인", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "보도자료", title: "사전 보도자료 비용 내부 품의 결재", offsetDays: -22, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "보도자료", title: "사전 보도자료 송출", offsetDays: -20, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "(사전/사후) 보도자료 완료", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "디자인물 문구 확인", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "백드롭, 포토월, 시상피켓 제작 및 내부 컨펌", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "백드롭, 포토월, 시상피켓 디자인 클라이언트 확인", offsetDays: -13, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "현수막 및 배너 제작 및 내부 컨펌", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "현수막 및 배너 디자인 클라이언트 확인", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "교재 디자인물 제작", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "명찰 및 명패(조명패, 심사위원 명패) 디자인물 제작", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "안내자료(ppt) 템플릿 디자인 제작", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "일정표 디자인물 제작", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "디자인물", title: "서명록 디자인물 제작", offsetDays: -15, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "행사 전체 디자인물 제작 완료", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력", title: "백드롭, 포토월, 시상피켓 주문관련 내부 품의 결재", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력", title: "백드롭, 포토월, 시상피켓 주문", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력", title: "백드롭, 포토월, 시상피켓 수령", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력", title: "현수막 및 배너 주문관련 내부 품의 결재", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력", title: "현수막 및 배너 주문", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력", title: "현수막 및 배너 수령", offsetDays: -7, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "행사 전체 디자인물 주문 및 수령 완료", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "케이터링", title: "케이터링 업체 확인", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "케이터링", title: "케이터링 관련 내용 전체 체크 (비고란 참고)", offsetDays: -20, quantity: null, note: "배달 가능 여부, 배달비 여부, 포장 상태 등" },
      { phase: "행사전", category: null, subcategory: "케이터링", title: "케이터링 업체 견적 요청", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "케이터링", title: "케이터링 주문 품의서 작성 및 내부 결재", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "야식", title: "야식 업체 확인", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "야식", title: "야식 관련 내용 전체 체크 (비고란 참고)", offsetDays: -20, quantity: null, note: "콜라 구매여부, 나무젓가락 개수, 배달여부, 위치, 금액, 전화번호" },
      { phase: "행사전", category: null, subcategory: "야식", title: "야식 업체 견적 요청", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "야식", title: "야식 주문 품의서 작성 및 내부결재", offsetDays: -10, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "케이터링 및 야식 업체 확정", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "참가인원", title: "최종 참가 인원 체크", offsetDays: -10, quantity: null, note: "불참 인원, 내부인력, 관계자 모두 포함" },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "내부인력 출발시간 및 이동방법 체크", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "출장신청서 내부 품의 결재", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "영상촬영 업체 확정", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "영상촬영 관련 일정 확인 및 내용 전달", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "영상촬영 및 제작비 내부 품의 결재", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "알바비 품의서 작성 및 내부결재", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "알바생 섭외 확정", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "알바생 정산 자료 수령 및 경영지원팀 전달", offsetDays: -10, quantity: null, note: "수락서, 통장사본, 신분증사본" },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "전문인력(강사, 심사위원, 멘토, 사회자) 섭외 리스트업 및 내부 컨펌", offsetDays: -28, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "전문인력(강사, 심사위원, 멘토, 사회자) 섭외 리스트 클라이언트 컨펌", offsetDays: -24, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "강사/심사위원/멘토/사회자 섭외 진행상황 체크", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "깅사/심사위원/멘토/사회자 배정 및 섭외 확정", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "깅사/심사위원/멘토/사회자 품의서 작성 및 내부결재", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "강의/진행/멘토링 수락서 송부", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "강사/심사위원/멘토/사회자 일정 세부내용 안내(전화)", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "강의/진행/멘토링 수락서 회신", offsetDays: -11, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "강사/심사위원/멘토 교통편 체크", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "투입인력", title: "강사/심사위원/멘토 관련 파일 회신", offsetDays: -11, quantity: null, note: "프로필, 통장사본, 신분증사본" },
      { phase: null, category: null, subcategory: "추진일정", title: "투입인력(내부인력, 강사, 관계자 등) 확정", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "대본", title: "사회자 대본 작성 및 내부 컨펌", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "대본", title: "사회자 대본 송부", offsetDays: -13, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "사회자 대본 확정", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "교재", title: "강의자료 취합", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "교재", title: "강의자료 내용 확인", offsetDays: -11, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "교재", title: "강의자료 클라이언트 컨펌", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "교재", title: "강의자료 전체 공유(사내 드라이브)", offsetDays: -8, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "교재", title: "교재 주문 내부결재 품의", offsetDays: -4, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "교재", title: "교재 주문", offsetDays: -4, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "교재", title: "교재 수령", offsetDays: -3, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "강의 교안 확인 및 교재 수령 완료", offsetDays: -5, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "명찰", title: "명찰 및 명패(조명패, 심사위원 명패) 제작", offsetDays: -10, quantity: null, note: "출력, 커팅,케이스 삽입" },
      { phase: "행사전", category: null, subcategory: "안내PPT", title: "오리엔테이션 PPT 자료 제작", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "안내PPT", title: "수료식 PPT 자료 제작", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "안내PPT", title: "야간 안전 안내 PPT 자료 제작", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "안내PPT", title: "전체 제작 PPT 및 필요 파일 USB 옮기기", offsetDays: -2, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "결과보고", title: "(사전) 결과보고서 작성", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "대기음악", title: "대기시간용 동영상 / 음악", offsetDays: -2, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "조편성표 제작 및 출력", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "방배정표 제작 및 출력", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "일정표 제작 및 출력 (전지 or 현수막)", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "서명록 제작 및 출력", offsetDays: -4, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "개인정보활용 및 사진촬영 동의서 내용 확인", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "개인정보활용 및 사진촬영 동의서 제작", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "개인정보활용 및 사진촬영 동의서 클라이언트 확인", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "개인정보활용 및 사진촬영 동의서 출력", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "상장 / 수료증 양식 기관 확인", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "상장 / 수료증 제작 및 출력", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "(1차) 캠프 운영 시나리오 작성 및 내부 회의", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "출력물", title: "(최종) 캠프 운영 시나리오 작성 및 출력", offsetDays: -7, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "캠프 관련 제작물 및 출력물 준비 완료", offsetDays: -2, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "설문조사", title: "설문 내용 구성 및 클라이언트 확인", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "설문조사", title: "모바일 설문조사 페이지 개설", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "설문조사", title: "모바일 설문조사 QR 코드 안내 PPT 준비", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "설문조사", title: "만족도 설문지 출력", offsetDays: -2, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "만족도 설문조사 준비 완료", offsetDays: -2, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "사전안내", title: "참가자 안내 메시지 작성 및 내부 컨펌", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "사전안내", title: "최종 참가자 오픈채팅방 개설", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "사전안내", title: "참가자 행사 안내 메시지 1차 송부", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "사전안내", title: "참가자 행사 안내 메시지 2차 송부", offsetDays: -2, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "사전안내", title: "참가자 행사 안내 메시지 추가 송부", offsetDays: -1, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "사전안내", title: "노쇼 방지를 위한 참여자 \\개별 통화", offsetDays: -1, quantity: null, note: "*장기사업이거나 회차별 동일 인원의 경우 첫번째 행사만 진행" },
      { phase: null, category: null, subcategory: "추진일정", title: "참가자 행사 관련 공지사항 전달", offsetDays: -1, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "온라인", title: "ZOOM 내부 품의 결재", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "온라인", title: "ZOOM 유료 서비스 활성화", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "온라인", title: "ZOOM 사전 접속 테스트 진행", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "온라인", title: "참가자 ZOOM 설치 및 관련 공지사항 전달", offsetDays: -5, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "온라인 진행 관련 준비 완료", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "준비물품", title: "(1차) 준비물품 전체 수량 체크 및 내부 품의 결재", offsetDays: -30, quantity: null, note: null },
      { phase: "행사전", category: null, subcategory: "준비물품", title: "(최종) 준비물품 체크리스트 확인", offsetDays: -2, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "준비물품 준비 완료", offsetDays: -2, quantity: null, note: null },
      { phase: "행사일", category: null, subcategory: "사전안내", title: "(시작 전) 참가자 최종 안내문자 송부", offsetDays: 0, quantity: null, note: null },
      { phase: "행사일", category: null, subcategory: "최종체크", title: "현장 세팅 및 투입인력 최종 연락(강사 및 알바생)", offsetDays: 0, quantity: null, note: null },
      { phase: "행사일", category: null, subcategory: "리허설", title: "리허설 진행", offsetDays: 0, quantity: null, note: null },
      { phase: "행사일", category: null, subcategory: "SNS", title: "SNS 업로드", offsetDays: 0, quantity: null, note: "페이스북, 인스타그램, 블로그" },
      { phase: null, category: null, subcategory: "추진일정", title: "당일 사전 준비 및 행사 진행", offsetDays: 0, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "투입인력", title: "투입인력(강사, 멘토, 심사위원) 감사문자 송부", offsetDays: 2, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "리뷰", title: "프로젝트 리뷰 회의", offsetDays: 3, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "리뷰", title: "프로젝트 리뷰 보고서 작성 및 공유", offsetDays: 14, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "완료보고", title: "체크리스트/운영시나리오 추가된 업무 공유", offsetDays: 14, quantity: null, note: "※ 프로젝트 리뷰 게시판 작성 내용에 추가(기존 양식에 없는 추가된 업무)" },
      { phase: "행사후", category: null, subcategory: "보도자료", title: "사후 보도자료 1차 작성 및 내부컨펌", offsetDays: 1, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "보도자료", title: "사후 보도자료 클라이언트 확인", offsetDays: 1, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "보도자료", title: "사후 보도자료 비용 내부 품의 결재", offsetDays: 1, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "보도자료", title: "사후 보도자료 송출", offsetDays: 2, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "사업파일", title: "노트북 사업 파일 확인 후 제거", offsetDays: 1, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "비용처리", title: "업체별 정산처리 (숙소 및 버스 등)", offsetDays: 7, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "비용처리", title: "인건비 정산처리 (강사, 심사위원 등)", offsetDays: 7, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "비용처리", title: "출장정산 및 보고서 내부품의", offsetDays: 2, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "결과보고", title: "결과보고서 50% 이상 작성", offsetDays: 7, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "결과보고", title: "결과보고서 완성", offsetDays: 8, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "결과보고", title: "결과보고서 송부", offsetDays: 10, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "결과보고", title: "결과보고서 수정사항 확인", offsetDays: 12, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "결과보고", title: "최종 결과보고서 구글드라이브 공유", offsetDays: 12, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "정산", title: "원본 서류 송부 or 폐기(발주처와 협의 필수)", offsetDays: 14, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "정산", title: "세금계산서 발급", offsetDays: 14, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "정산", title: "추가 정산서류 확인", offsetDays: 14, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "정산", title: "사업비 입금 확인", offsetDays: 21, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "정산", title: "사업비 입금 후 발주기관 종료 인사 전화", offsetDays: 21, quantity: null, note: "* 사업 수행 관련 해피콜" },
      { phase: "행사후", category: null, subcategory: "완료보고", title: "완료요약보고서 작성 및 내부 완료보고", offsetDays: 21, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "완료보고", title: "체크리스트 완성본 공유", offsetDays: 21, quantity: null, note: null },
      { phase: "행사후", category: null, subcategory: "완료보고", title: "사업 서류파일 리스트업 및 최종 보고", offsetDays: 21, quantity: null, note: null },
      { phase: null, category: null, subcategory: "추진일정", title: "정산 및 사업 종료", offsetDays: 21, quantity: null, note: null },
    ],
  },
  {
    kind: "typed",
    name: "유형별 체크리스트",
    sortOrder: 1,
    items: [
      { phase: "행사전", category: "캠프", subcategory: "견학/탐방", title: "견학 장소 리스트업 및 내부 컨펌", offsetDays: -20, quantity: null, note: "일정 가능여부, 금액, 위치, 견학 방법 등" },
      { phase: "행사전", category: "캠프", subcategory: "견학/탐방", title: "견학 장소 클라이언트 확인", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "견학/탐방", title: "견학지 최종 확정", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "견학/탐방", title: "견학지별 내부 품의", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "견학/탐방", title: "견학지별 일정 등 관련 사항 1차 전달", offsetDays: -15, quantity: null, note: "대상/인원, 일정/시간, 견학 방법 등" },
      { phase: "행사전", category: "캠프", subcategory: "견학/탐방", title: "견학지별 일정 등 관련 사항 최종 전달", offsetDays: -10, quantity: null, note: null },
      { phase: null, category: "캠프", subcategory: "추진일정", title: "견학(탐방) 장소 확정", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "시장조사", title: "시장조사 장소 리스트업", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "시장조사", title: "시장조사 장소 리스트 클라이언트 컨펌", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "시장조사", title: "시장조사 장소 안내문(PPT, hwp) 제작 및 내부 컨펌", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "시장조사", title: "시장조사 보고서 양식 제작 및 내부 컨펌", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "시장조사", title: "시장조사 보고서 양식 클라이언트 컨펌", offsetDays: -13, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "시장조사", title: "시장조사 보고서 작성 안내문(PPT, hwp) 제작 및 내부 컨펌", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "시장조사", title: "시장조사 보고서 출력", offsetDays: -5, quantity: null, note: null },
      { phase: null, category: "캠프", subcategory: "추진일정", title: "시장조사 장소 확정 및 시장조사 보고서 제작 완료", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "여행자보험", title: "여행자보험 진행 여부 확인", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "여행자보험", title: "여행자보험 가입 명단 확정", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "여행자보험", title: "여행자보험 가입 시 대상자 주민번호 확보", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "여행자보험", title: "여행자보험 가입 요청 메일 송부", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "여행자보험", title: "여행자보험 내부 품의 결재", offsetDays: -13, quantity: null, note: null },
      { phase: "행사전", category: "캠프", subcategory: "여행자보험", title: "여행자보험 가입 확정", offsetDays: -10, quantity: null, note: null },
      { phase: null, category: "캠프", subcategory: "추진일정", title: "여행자보험 가입", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "사전진단", title: "사전 기업 진단 설문 구성 및 내부 컨펌", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "사전진단", title: "사전 기업 진단 설문 클라이언트 컨펌", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "사전진단", title: "모바일 진단 페이지 개설", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "사전진단", title: "모바일 진단 링크 송부(to. 참여팀)", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "사전진단", title: "모바일 진단 결과 1차 취합", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "사전진단", title: "모바일 진단 결과 2차 취합", offsetDays: -12, quantity: null, note: null },
      { phase: null, category: "멘토링/컨설팅", subcategory: "추진일정", title: "사전 기업 진단 링크 개설 및 취합", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "진단컨설팅", title: "진단컨설팅 참가인원(팀) 및 매칭(일정표) 확정", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "진단컨설팅", title: "진단분석보고서 양식 제작 및 내부 컨펌", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "진단컨설팅", title: "진단분석보고서 양식 클라이언트 컨펌", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "진단컨설팅", title: "기업별 진단분석보고서 양식 제작", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "진단컨설팅", title: "기업별 진단분석보고서 양식 출력", offsetDays: -14, quantity: null, note: null },
      { phase: "행사후", category: "멘토링/컨설팅", subcategory: "진단컨설팅", title: "기업별 진단분석보고서 1차 취합", offsetDays: 1, quantity: null, note: null },
      { phase: "행사후", category: "멘토링/컨설팅", subcategory: "진단컨설팅", title: "기업별 진단분석보고서 최종 취합", offsetDays: 3, quantity: null, note: null },
      { phase: null, category: "멘토링/컨설팅", subcategory: "추진일정", title: "진단분석보고서 양식 확정", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "매칭", title: "멘토링 참가인원(팀) 확정", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "매칭", title: "참가자 - 멘토 1차 매칭", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "매칭", title: "참가자 - 멘토 최종 확정", offsetDays: -8, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "매칭", title: "멘토링 매칭 안내 자료 제작", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "매칭", title: "(오프라인) 멘토링 보고서 출력", offsetDays: -5, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "매칭", title: "(온라인) 매칭 안내 메일 송부(to. 참가팀, 멘토)", offsetDays: -10, quantity: null, note: null },
      { phase: null, category: "멘토링/컨설팅", subcategory: "추진일정", title: "멘토링/컨설팅 매칭 확정", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "보고서", title: "멘토링 보고서 양식 작성 및 내부 컨펌", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "보고서", title: "멘토링 보고서 양식 클라이언트 확인", offsetDays: -13, quantity: null, note: null },
      { phase: "행사후", category: "멘토링/컨설팅", subcategory: "보고서", title: "(온라인) 멘토링 보고서 1차(회차별 or 월별) 취합", offsetDays: 7, quantity: null, note: "과업 일정(월별 or 1주일 간격 등)에 따라 마감일 계획일 변경" },
      { phase: "행사후", category: "멘토링/컨설팅", subcategory: "보고서", title: "(온라인) 멘토링 보고서 2차(회차별 or 월별) 취합", offsetDays: 14, quantity: null, note: null },
      { phase: "행사후", category: "멘토링/컨설팅", subcategory: "보고서", title: "(온라인) 멘토링 보고서 최종(회차별 or 월별) 취합", offsetDays: 21, quantity: null, note: null },
      { phase: "행사후", category: "멘토링/컨설팅", subcategory: "보고서", title: "(오프라인) 멘토링 보고서 취합", offsetDays: 2, quantity: null, note: null },
      { phase: null, category: "멘토링/컨설팅", subcategory: "추진일정", title: "멘토링 보고서 양식 제작 및 취합", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "만족도", title: "멘토링 만족도 설문 제작 및 내부 컨펌", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: "멘토링/컨설팅", subcategory: "만족도", title: "멘토링 만족도 설문 클라이언트 컨펌", offsetDays: -20, quantity: null, note: null },
      { phase: "행사후", category: "멘토링/컨설팅", subcategory: "만족도", title: "(온라인) 멘토링 만족도 설문 링크 1차(회차별 or 월별) 송부", offsetDays: -20, quantity: null, note: "멘토링/컨설팅 만족도 설문 송부: 팀별 컨설팅 일정에 맞춰" },
      { phase: "행사후", category: "멘토링/컨설팅", subcategory: "만족도", title: "(온라인) 멘토링 만족도 설문 링크 2차(회차별 or 월별) 송부", offsetDays: -20, quantity: null, note: null },
      { phase: "행사후", category: "멘토링/컨설팅", subcategory: "만족도", title: "(온라인) 멘토링 만족도 설문 링크 최종(회차별 or 월별) 송부", offsetDays: -20, quantity: null, note: null },
      { phase: null, category: "멘토링/컨설팅", subcategory: "추진일정", title: "매칭 확정 및 멘토링 보고서 취합", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "발표", title: "발표 자료 제출 안내(to. 참가팀)", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "발표", title: "발표 자료 1차 제출 확인 및 미제출팀 제출 재요청", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "발표", title: "발표 자료 최종 취합", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "발표", title: "발표 자료 PC 세팅 or 출력", offsetDays: -5, quantity: null, note: null },
      { phase: null, category: "데모데이", subcategory: "추진일정", title: "발표자료 제출 안내 및 취합 완료", offsetDays: -24, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "평가", title: "심사평가표 제작 및 내부컨펌", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "평가", title: "심사평가표 클라이언트 확인", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "평가", title: "심사평가표 출력", offsetDays: -2, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "평가", title: "점수합산표(엑셀) 양식 제작 및 내부 컨펌", offsetDays: -20, quantity: null, note: null },
      { phase: "행사후", category: "데모데이", subcategory: "평가", title: "팀별 심사평가표 취합", offsetDays: 1, quantity: null, note: null },
      { phase: null, category: "데모데이", subcategory: "추진일정", title: "심사평가표 확정", offsetDays: -24, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "시상금", title: "상금수령신청서 작성 및 내부 컨펌", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "데모데이", subcategory: "시상금", title: "상금수령신청서 클라이언트 컨펌", offsetDays: -7, quantity: null, note: "※ 제세공과금(4.4%) 공제됨 사전 전달 필수" },
      { phase: "행사전", category: "데모데이", subcategory: "시상금", title: "상금수령신청서 출력", offsetDays: -7, quantity: null, note: null },
      { phase: "행사후", category: "데모데이", subcategory: "시상금", title: "상금수령신청서 취합", offsetDays: -20, quantity: null, note: null },
      { phase: null, category: "데모데이", subcategory: "추진일정", title: "상금수령신청서 확정", offsetDays: -24, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "판넬 제작 필요정보 양식 제작 및 내부 컨펌", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "판넬 제작 필요정보 양식 클라이언트 확인", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "판넬 제작 필요정보 양식 전달(to. 참가팀)", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "판넬 제작 필요정보 취합", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "판넬 디자인 시안 제작 및 내부 컨펌", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "판넬 디자인 시안 클라이언트 확인", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "참가팀별 판넬 제작", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "참가팀별 판넬 제작비 내부 결재", offsetDays: -10, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "참가팀별 판넬 제작 요청", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "판넬", title: "참가팀별 판넬 수령", offsetDays: -3, quantity: null, note: null },
      { phase: null, category: "전시행사", subcategory: "추진일정", title: "판넬 수령 완료", offsetDays: -3, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "현장 실측 사항 확인", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "부스 견적 확인", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "부스 브로슈어 클라이언트 전달", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "부스 설치 업체 선정", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "업체 견적서 회신 및 결제 방법 확정", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "부스 배치표 확정", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "부스 디자인물 양식 제작 및 내부 컨펌", offsetDays: -15, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "부스 디자인물 양식 클라이언트 컨펌", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "기업별 부스 양식 삽입 요청", offsetDays: -12, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "기업별 부스 삽입 내용 취합", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "기업별 부스 디자인 시안 확정", offsetDays: -14, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "부스 설치 일정 및 설치 담당자 정보 확인", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: "전시행사", subcategory: "부스", title: "부스 설치 완료 여부 확인", offsetDays: -7, quantity: null, note: null },
      { phase: null, category: "전시행사", subcategory: "추진일정", title: "부스 설치 완료 여부 확인", offsetDays: -3, quantity: null, note: null },
      { phase: "행사전", category: "기타", subcategory: "스케치영상", title: "촬영, 영상 업체 선정", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: "기타", subcategory: "스케치영상", title: "영상 제작 관련 사전 회의", offsetDays: -23, quantity: null, note: null },
      { phase: "행사전", category: "기타", subcategory: "스케치영상", title: "영상 제작 시나리오(+인터뷰지) 확정", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: "기타", subcategory: "스케치영상", title: "스케치영상 계약 및 내부 품의 결재", offsetDays: -20, quantity: null, note: null },
      { phase: "행사전", category: "기타", subcategory: "스케치영상", title: "스케치영상 1차본 확인 및 클라이언트 컨펌 요청", offsetDays: -18, quantity: null, note: null },
      { phase: "행사전", category: "기타", subcategory: "스케치영상", title: "스케치영상 최종본 확인 및 클라이언트 컨펌 요청", offsetDays: -7, quantity: null, note: null },
      { phase: null, category: "기타", subcategory: "추진일정", title: "스케치영상 확정", offsetDays: -7, quantity: null, note: null },
      { phase: "행사전", category: "기타", subcategory: "역량진단", title: "(창업/경영) 역량진단검사 페이지 제작", offsetDays: -25, quantity: null, note: null },
      { phase: "행사전", category: "기타", subcategory: "역량진단", title: "(창업/경영) 역량진단검사 관련 안내문자 송부", offsetDays: -23, quantity: null, note: null },
      { phase: "행사전", category: "기타", subcategory: "역량진단", title: "(창업/경영) 역량진단검사 결과 취합", offsetDays: -20, quantity: null, note: null },
      { phase: null, category: "기타", subcategory: "추진일정", title: "창업역량진단검사 취합", offsetDays: -7, quantity: null, note: null },
    ],
  },
  {
    kind: "kickoff",
    name: "착수보고회 체크리스트",
    sortOrder: 2,
    items: [
      { phase: null, category: "준비물품", subcategory: null, title: "명함", offsetDays: null, quantity: null, note: "준비 완료 여부 확인" },
      { phase: null, category: "준비물품", subcategory: null, title: "착수보고 자료", offsetDays: null, quantity: null, note: "준비 완료 여부 확인" },
      { phase: null, category: "준비물품", subcategory: null, title: "다이어리 및 필기구", offsetDays: null, quantity: null, note: "준비 완료 여부 확인" },
      { phase: null, category: "전체", subcategory: null, title: "계약 시점(일정) 확인 및 방문 계약 여부 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "전체", subcategory: null, title: "발주처 및 렛츠 소통 담당자 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "전체", subcategory: null, title: "발주처 및 소통 담당자 유의사항 확인", offsetDays: null, quantity: null, note: "(장기 휴가 계획, 내부 결재가 오래걸리는 편인지, 담당자 변경 가능성 여부 등)" },
      { phase: null, category: "전체", subcategory: null, title: "마감일 체크리스트 전달", offsetDays: null, quantity: null, note: "발주처에게 착수보고때 전달하여 원활한 소통 및 업무 진행 목적" },
      { phase: null, category: "전체", subcategory: null, title: "결과보고 및 완료계 최종 제출일 확인", offsetDays: null, quantity: null, note: "(계약 일정 전체 확인)" },
      { phase: null, category: "전체", subcategory: null, title: "비용 정산 프로세스 확인", offsetDays: null, quantity: null, note: "(총액 계약인지, 비용 지출 내역 증빙 필요한지)" },
      { phase: null, category: "전체", subcategory: null, title: "프로그램 내용 및 일정 확인 및 확정", offsetDays: null, quantity: null, note: "(확정 불가시, 언제까지 확정할 것인지 일정 기록)" },
      { phase: null, category: "전체", subcategory: null, title: "프로그램 참가자 최종 확정일", offsetDays: null, quantity: null, note: "(예: 1/21 행사의 경우, 1/15 최종 확정, 이후 변경 불가)" },
      { phase: null, category: "전체", subcategory: null, title: "이번 사업 운영에 더욱 신경써야 하는 부분 유무 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "전체", subcategory: null, title: "(담당자)장기연차 관련사항 사전 전달 요청", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "전체", subcategory: null, title: "강사/멘토/심사위원 섭외 진행처 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "전체", subcategory: null, title: "(기획안/견적서 포함의 경우) 보도자료 배포시점 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "전체", subcategory: null, title: "현수막/배너/교재 출력물 수량 및 발주처 요구사항 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "전체", subcategory: null, title: "영상자료 납품 필요 여부", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "전체", subcategory: null, title: "발주처 명의의 참가자 협조 공문 사전 요청", offsetDays: null, quantity: null, note: "(오프라인 필참시 - 대학교, 회사 제출용)" },
      { phase: null, category: "모집 X", subcategory: null, title: "최종 참가자 명단 전달 일정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "모집 X", subcategory: null, title: "참가자 주의사항 확인", offsetDays: null, quantity: null, note: "예민한 사항이나 주의가 필요한 인물" },
      { phase: null, category: "모집 O", subcategory: null, title: "발주처 보유 홍보리스트 유무 확인 및 사전 요청", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "모집 O", subcategory: null, title: "참가자 자격 조건 확인", offsetDays: null, quantity: null, note: "(지역제한, 예비/초기/도약, 학생/ 일반인 등)" },
      { phase: null, category: "모집 O", subcategory: null, title: "참가자 사업 분야 확인", offsetDays: null, quantity: null, note: "(예: IT, BT, 관광 등)" },
      { phase: null, category: "모집 O", subcategory: null, title: "유료 홍보 비용 조정 (비용상한/비목추가)", offsetDays: null, quantity: null, note: "(출력 및 부착 비용, 온라인 홍보비용 등)" },
      { phase: null, category: "모집 O", subcategory: null, title: "발주처 명의의 홍보 협조 공문 사전 요청", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "모집 O", subcategory: null, title: "심사여부 및 심사방식", offsetDays: null, quantity: null, note: "(심사평가표 및 심사위원 사전협의)" },
      { phase: null, category: "모집 O", subcategory: null, title: "팀으로 신청시 선발 후 추가 인원 승낙여부", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "참가자", subcategory: null, title: "(참여인원이 중요한 경우) 노쇼 인원 대책 관련 논의", offsetDays: null, quantity: null, note: "예) 예비팀 선발, 참석이벤트, 수료기준 지정 등" },
      { phase: null, category: "숙박형", subcategory: null, title: "개인정보수집을 위한 공문 사전 요청", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙박형", subcategory: null, title: "야간관리 필요 여부", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙박형", subcategory: null, title: "다과 박스 및 야식 필요 여부", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙박형", subcategory: null, title: "(여행자 보험 가입시) 담당자 보험 가입여부 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "시상O", subcategory: null, title: "(당일 시상시) 상장 및 피켓전달 여부 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "시상O", subcategory: null, title: "(시상금 전달 시) 별도 서류 필요 유무 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "시상O", subcategory: null, title: "시상자 방향 논의", offsetDays: null, quantity: null, note: "(주관사/심사위원/렛츠 中)" },
      { phase: null, category: "버스 대절", subcategory: null, title: "버스인솔자 필요 여부", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "버스 대절", subcategory: null, title: "버스 內 생수 및 간식 필요여부", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "버스 대절", subcategory: null, title: "버스 미탑승자 인원 비용지급 여부", offsetDays: null, quantity: null, note: "(교통비 별도 지급 여부)" },
      { phase: null, category: "온라인", subcategory: null, title: "(Zoom) 영상 녹화본 제출 여부", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "온라인", subcategory: null, title: "(Zoom) 영상 녹화본 배포 여부", offsetDays: null, quantity: null, note: null },
    ],
  },
  {
    kind: "deadline",
    name: "마감일 체크리스트",
    sortOrder: 3,
    items: [
      { phase: null, category: null, subcategory: null, title: "(발주처에서 진행 시) 최종 선정 명단 공유", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "(발주처에서 진행 시) 취합 자료 공유(신청서, 사업계획서, 발표자료 등)", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "(발주처에서 진행 시) 강의장 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "(발주처에서 진행 시) 숙소 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "(발주처에서 진행 시) 섭외인력(강사/멘토/심사위원 등) 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "기념품 항목 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "디자인물 시안(현수막, 배너, 포스터, 피켓 등) 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "인사말(개회사) 진행 여부 및 진행자 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "내부 참가 명단 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "내외빈(VIP) 명단 확정", offsetDays: null, quantity: null, note: null },
      { phase: null, category: null, subcategory: null, title: "(시상식) 시상자 확정", offsetDays: null, quantity: null, note: null },
    ],
  },
  {
    kind: "venue",
    name: "숙소 및 강의장 체크리스트",
    sortOrder: 4,
    items: [
      { phase: null, category: "숙소", subcategory: null, title: "객실 타입 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "식사 메뉴 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "야식 가능여부 및 쓰레기 분리수거 체크", offsetDays: null, quantity: null, note: "쓰레기는 지하 일층 분리수거장에서 일괄 진행" },
      { phase: null, category: "숙소", subcategory: null, title: "방키 수령 및 입실시간 체크", offsetDays: null, quantity: null, note: "키 직접 수령" },
      { phase: null, category: "숙소", subcategory: null, title: "퇴실시간 및 방키반납시간 체크", offsetDays: null, quantity: null, note: "키 직접 반납" },
      { phase: null, category: "숙소", subcategory: null, title: "숙소 내 정수기, 컵 유무 체크", offsetDays: null, quantity: null, note: "입실 시 참가자 생수 1개씩 제공" },
      { phase: null, category: "숙소", subcategory: null, title: "냉온수 여부 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "냉장고 사용 / 대여 여부 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "숙소 내 무선인터넷 유무 체크", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "숙소 내 물품 체크", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "냉난방 시설 체크", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "숙소 결제 방법 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "주차 방법 및 주차권 수량 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "주차장 크기, 주차 지원 여부", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "숙소", subcategory: null, title: "조식 진행 방법 확인(쿠폰, 카운팅 등)", offsetDays: null, quantity: null, note: "식사 인원 카운팅 or 조식 쿠폰 등" },
      { phase: null, category: "숙소", subcategory: null, title: "현장답사 기타 확인사항", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "빔프로젝터 작동여부, 사이즈 체크", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "강의장 인터넷 사용방법 체크", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "마이크 체크(개수, 유무선), 강의장 컴퓨터(노트북)", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "강의장 내 정수기 체크(위치 및 냉온수기능) , 물컵", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "음향기기 종류 체크", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "강의장 내 테이블 배치 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "강의장 내 테이블 배치 변경 가능여부 확인", offsetDays: null, quantity: null, note: "대관처에 요청하면 변경 가능 vs 운영사에서 직접 변경해야 함" },
      { phase: null, category: "강의장", subcategory: null, title: "강의장 테이블 및 의자 추가 수량 확보 가능여부 확인", offsetDays: null, quantity: null, note: "인원 추가 및 다과 세팅 테이블에 따른 수량 추가 확보" },
      { phase: null, category: "강의장", subcategory: null, title: "현수막 사이즈 및 부착 방법 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "배너 설치 위치 확인", offsetDays: null, quantity: null, note: "행사장 접근이 어려울 경우 배너 필요여부 확인" },
      { phase: null, category: "강의장", subcategory: null, title: "백드롭/포토월 사이즈 및 게시방법", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "화장실 위치 및 특징 확인", offsetDays: null, quantity: null, note: "프로그램 특성에 따라 여성화장실 위치, 심야 화장실 폐쇄여부 확인" },
      { phase: null, category: "강의장", subcategory: null, title: "리허설 및 사전세팅시간 확인", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "강의장", subcategory: null, title: "강의장 내 음식/다과 취식 가능여부 확인", offsetDays: null, quantity: null, note: "강의장 내 음식 섭취할 경우" },
      { phase: null, category: "강의장", subcategory: null, title: "사회자 단상, 포디움 보유 여부 확인", offsetDays: null, quantity: null, note: null },
    ],
  },
  {
    kind: "supplies",
    name: "준비물품 체크리스트",
    sortOrder: 5,
    items: [
      { phase: null, category: "준비품", subcategory: null, title: "펜 케이스 (심사위원 물품)", offsetDays: null, quantity: "인원별", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "지우개 (심사위원 물품)", offsetDays: null, quantity: "인원별", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "3색 펜Set (심사위원 물품)", offsetDays: null, quantity: "인원별", note: "플러스팬으로 3색 준비" },
      { phase: null, category: "준비품", subcategory: null, title: "연필 (심사위원 물품)", offsetDays: null, quantity: "인원별", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "명패(출력물) (+케이스) (심사위원 물품)", offsetDays: null, quantity: "인원별", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "멀티탭", offsetDays: null, quantity: "5", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "노트북 (내부용)", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "스마트 포인터", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "카메라 충전기 및 여분 배터리", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "카메라 리더기", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "색연필", offsetDays: null, quantity: "5", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "사인펜", offsetDays: null, quantity: "5", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "라벨지", offsetDays: null, quantity: "20", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "화이트보드 세트(화이트보드판 + 보드마카 3종)", offsetDays: null, quantity: "5", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "추첨표(출력물)", offsetDays: null, quantity: "20", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "추첨박스", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "게임머니", offsetDays: null, quantity: "100", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "명찰(출력물) (+케이스)", offsetDays: null, quantity: "30", note: "참가자, 관계자, 운영인력, 공명찰" },
      { phase: null, category: "준비품", subcategory: null, title: "조명패(출력물) (+케이스)", offsetDays: null, quantity: "5", note: "필요시 여분 포함" },
      { phase: null, category: "준비품", subcategory: null, title: "수료증(출력물) (+케이스)", offsetDays: null, quantity: "20", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "서명록(출력물) (+케이스)", offsetDays: null, quantity: "1", note: "필요시 여분 포함" },
      { phase: null, category: "준비품", subcategory: null, title: "마이크 네임텍", offsetDays: null, quantity: "5", note: "마이크 고정용 테이프 포함" },
      { phase: null, category: "준비품", subcategory: null, title: "일정표(출력물)", offsetDays: null, quantity: "5", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "교재", offsetDays: null, quantity: "20", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "현수막", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "배너 및 배너대", offsetDays: null, quantity: "3", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "A4용지", offsetDays: null, quantity: "50", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "프린터", offsetDays: null, quantity: "50", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "전지 or 4절지", offsetDays: null, quantity: "10", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "갑티슈", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "물티슈", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "종이컵", offsetDays: null, quantity: "100", note: "종이컵 1줄당 50개입" },
      { phase: null, category: "준비품", subcategory: null, title: "강사 및 심사위원 제공용 물", offsetDays: null, quantity: "20", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "숙소용 물", offsetDays: null, quantity: "20", note: "숙소 내 정수기 or 물이 없을 경우" },
      { phase: null, category: "준비품", subcategory: null, title: "경품, 시상품", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "준비품", subcategory: null, title: "간식(쿠키, 과자, 과일, 음료 등)", offsetDays: null, quantity: "30인분", note: null },
      { phase: null, category: "준비품", subcategory: null, title: "간식바구니", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "준비품", subcategory: null, title: "프린터기", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "준비품", subcategory: null, title: "다과 테이블보", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "준비품", subcategory: null, title: "쓰레기봉투(분리수거용)", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "문구함", subcategory: null, title: "가위, 칼", offsetDays: null, quantity: "각 2개", note: null },
      { phase: null, category: "문구함", subcategory: null, title: "테이프류 (투명 / 양면 / 박스 / 청)", offsetDays: null, quantity: "각 1개", note: null },
      { phase: null, category: "문구함", subcategory: null, title: "압정", offsetDays: null, quantity: "1묶음", note: null },
      { phase: null, category: "문구함", subcategory: null, title: "자석", offsetDays: null, quantity: "1묶음", note: null },
      { phase: null, category: "문구함", subcategory: null, title: "건전지 (AA, AAA)", offsetDays: null, quantity: "각 5개", note: null },
      { phase: null, category: "문구함", subcategory: null, title: "매직 3종(검은색, 빨간색, 파란색)", offsetDays: null, quantity: "2세트", note: "사용 가능 여부 확인 필요" },
      { phase: null, category: "문구함", subcategory: null, title: "보드마카 3종(검은색, 빨간색, 파란색)+지우개", offsetDays: null, quantity: "2세트", note: "사용 가능 여부 확인 필요" },
      { phase: null, category: "문구함", subcategory: null, title: "포스트잇", offsetDays: null, quantity: "3묶음", note: null },
      { phase: null, category: "문구함", subcategory: null, title: "풀, 스카치 테이프", offsetDays: null, quantity: "각 2개", note: null },
      { phase: null, category: "문구함", subcategory: null, title: "스테인플러(+리필심)", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "문구함", subcategory: null, title: "볼펜", offsetDays: null, quantity: "30개", note: null },
      { phase: null, category: "문구함", subcategory: null, title: "나이스러", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "붕대, 밴드", offsetDays: null, quantity: "각 1묶음", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "상처연고", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "멀미약", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "진통제", offsetDays: null, quantity: "2개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "급체약/소화제", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "침 (체했을때)", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "지사제", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "파스", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "모기약", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "감기약", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "두통약", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "구급함", subcategory: null, title: "체온계", offsetDays: null, quantity: "1개", note: null },
      { phase: null, category: "온라인물품", subcategory: null, title: "마이크", offsetDays: null, quantity: "2", note: null },
      { phase: null, category: "온라인물품", subcategory: null, title: "화상캠", offsetDays: null, quantity: "2", note: null },
      { phase: null, category: "온라인물품", subcategory: null, title: "멀티비전", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "온라인물품", subcategory: null, title: "랜선", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "온라인물품", subcategory: null, title: "HDMI선", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "온라인물품", subcategory: null, title: "단상", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "온라인물품", subcategory: null, title: "이어폰", offsetDays: null, quantity: "2", note: null },
      { phase: null, category: "온라인물품", subcategory: null, title: "테스트용 PC", offsetDays: null, quantity: "2", note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "플라스틱 집게", offsetDays: null, quantity: "10", note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "깃발꽂이(+출력물)", offsetDays: null, quantity: "50", note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "유산지 (페이퍼, 컵)", offsetDays: null, quantity: "1묶음", note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "일회용 접시", offsetDays: null, quantity: "60", note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "일회용 포크", offsetDays: null, quantity: "60", note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "세팅용 꽃(+꽃병)", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "음료 디스펜서", offsetDays: null, quantity: "1", note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "음료 보틀(유리 케이스)", offsetDays: null, quantity: "2", note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "케이터링용 쟁반, 바구니", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "슈가 파우더", offsetDays: null, quantity: "1묶음", note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "스탠드 안내판(+안내문)", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "케이터링(내부준비용)", subcategory: null, title: "음료 보틀", offsetDays: null, quantity: null, note: null },
      { phase: null, category: "발표/평가", subcategory: null, title: "꽃다발", offsetDays: null, quantity: "10", note: null },
      { phase: null, category: "발표/평가", subcategory: null, title: "타이머", offsetDays: null, quantity: "50", note: null },
      { phase: null, category: "발표/평가", subcategory: null, title: "시상피켓", offsetDays: null, quantity: "1묶음", note: null },
      { phase: null, category: "발표/평가", subcategory: null, title: "상장(출력물) (+케이스)", offsetDays: null, quantity: "60", note: null },
    ],
  },
  {
    kind: "supplies",
    name: "팀빌딩(스트롱브릿지) 준비물품",
    sortOrder: 6,
    items: [
      { phase: null, category: null, subcategory: null, title: "포맥스(나무막대 / 5T)", offsetDays: null, quantity: null, note: "조당 4개씩" },
      { phase: null, category: null, subcategory: null, title: "마분지(A4)", offsetDays: null, quantity: null, note: "조당 2장씩" },
      { phase: null, category: null, subcategory: null, title: "종이빨대", offsetDays: null, quantity: null, note: "조당 20개씩" },
      { phase: null, category: null, subcategory: null, title: "철사(1개당 굵기 3.22mm * 길이 2M)", offsetDays: null, quantity: null, note: "조당 1개씩" },
      { phase: null, category: null, subcategory: null, title: "종이테이프(1개당 굵기 15mm * 길이 40M)", offsetDays: null, quantity: null, note: "조당 1개씩" },
      { phase: null, category: null, subcategory: null, title: "가위", offsetDays: null, quantity: null, note: "조당 2개씩" },
      { phase: null, category: null, subcategory: null, title: "노끈(1개당 50cm)", offsetDays: null, quantity: null, note: "조당 1개씩" },
      { phase: null, category: null, subcategory: null, title: "플라스틱 자(1개당 50cm)", offsetDays: null, quantity: null, note: "조당 1개씩" },
      { phase: null, category: null, subcategory: null, title: "장난감 자동차", offsetDays: null, quantity: null, note: "전체 1개" },
      { phase: null, category: null, subcategory: null, title: "무게 측정용 아령 세트", offsetDays: null, quantity: null, note: "전체 1개" },
      { phase: null, category: null, subcategory: null, title: "S고리", offsetDays: null, quantity: null, note: "전체 2개" },
      { phase: null, category: null, subcategory: null, title: "무게 측정용 주머니", offsetDays: null, quantity: null, note: "전체 1개" },
      { phase: null, category: null, subcategory: null, title: "타이머", offsetDays: null, quantity: null, note: "전체 1개" },
      { phase: null, category: null, subcategory: null, title: "강의자료(PPT)", offsetDays: null, quantity: null, note: "전체 1개" },
      { phase: null, category: null, subcategory: null, title: "진행자 확정", offsetDays: null, quantity: null, note: "1명" },
      { phase: null, category: null, subcategory: null, title: "사진 및 영상 촬영자 확정", offsetDays: null, quantity: null, note: "1명" },
      { phase: null, category: null, subcategory: null, title: "미션 결과 기입자 확정", offsetDays: null, quantity: null, note: "1명" },
      { phase: null, category: null, subcategory: null, title: "진행 보조자 확정", offsetDays: null, quantity: null, note: "1명" },
    ],
  },
  {
    kind: "supplies",
    name: "팀빌딩(롤러코스터) 준비물품",
    sortOrder: 7,
    items: [
      { phase: null, category: null, subcategory: null, title: "A4용지", offsetDays: null, quantity: null, note: "조당 20장씩" },
      { phase: null, category: null, subcategory: null, title: "스카치테이프", offsetDays: null, quantity: null, note: "조당 2개씩" },
      { phase: null, category: null, subcategory: null, title: "가위", offsetDays: null, quantity: null, note: "조당 2개씩" },
      { phase: null, category: null, subcategory: null, title: "탁구공", offsetDays: null, quantity: null, note: "조당 1개씩" },
      { phase: null, category: null, subcategory: null, title: "타이머", offsetDays: null, quantity: null, note: "전체 1개" },
      { phase: null, category: null, subcategory: null, title: "강의자료(PPT)", offsetDays: null, quantity: null, note: "전체 1개" },
      { phase: null, category: null, subcategory: null, title: "진행자 확정", offsetDays: null, quantity: null, note: "1명" },
      { phase: null, category: null, subcategory: null, title: "사진 및 영상 촬영자 확정", offsetDays: null, quantity: null, note: "1명" },
      { phase: null, category: null, subcategory: null, title: "시간 측정자 확정", offsetDays: null, quantity: null, note: "1명" },
      { phase: null, category: null, subcategory: null, title: "미션 결과 기입자 확정", offsetDays: null, quantity: null, note: "1명" },
    ],
  },
  {
    kind: "supplies",
    name: "팀빌딩(마시멜로우) 준비물품",
    sortOrder: 8,
    items: [
      { phase: null, category: null, subcategory: null, title: "마시멜로우", offsetDays: null, quantity: null, note: "조당 1개씩" },
      { phase: null, category: null, subcategory: null, title: "스파게티면", offsetDays: null, quantity: null, note: "조당 30가닥씩" },
      { phase: null, category: null, subcategory: null, title: "가위", offsetDays: null, quantity: null, note: "조당 1개씩" },
      { phase: null, category: null, subcategory: null, title: "스카치테이프", offsetDays: null, quantity: null, note: "조당 1개씩" },
      { phase: null, category: null, subcategory: null, title: "줄자", offsetDays: null, quantity: null, note: "전체 1개" },
      { phase: null, category: null, subcategory: null, title: "강의자료(PPT)", offsetDays: null, quantity: null, note: "전체 1개" },
      { phase: null, category: null, subcategory: null, title: "진행자 확정", offsetDays: null, quantity: null, note: "1명" },
      { phase: null, category: null, subcategory: null, title: "사진 및 영상 촬영자 확정", offsetDays: null, quantity: null, note: "1명" },
      { phase: null, category: null, subcategory: null, title: "미션 결과 기입자 확정", offsetDays: null, quantity: null, note: "1명" },
    ],
  },
];
